<!DOCTYPE assembly [
        <!ELEMENT assembly (id|formats|fileSets|dependencySets)*>
        <!ATTLIST assembly
                xmlns CDATA #REQUIRED
                xmlns:xsi CDATA #REQUIRED
                xsi:schemaLocation CDATA #REQUIRED>
        <!ELEMENT id (#PCDATA)>
        <!ELEMENT formats (format)*>
        <!ELEMENT format (#PCDATA)>
        <!ELEMENT fileSets (fileSet)*>
        <!ELEMENT fileSet (directory|outputDirectory|fileMode|includes|directoryMode)*>
        <!ELEMENT directory (#PCDATA)>
        <!ELEMENT outputDirectory (#PCDATA)>
        <!ELEMENT fileMode (#PCDATA)>
        <!ELEMENT includes (include)*>
        <!ELEMENT include (#PCDATA)>
        <!ELEMENT directoryMode (#PCDATA)>
        <!ELEMENT dependencySets (dependencySet)*>
        <!ELEMENT dependencySet (outputDirectory|useProjectArtifact|fileMode|directoryMode|scope)*>
        <!ELEMENT useProjectArtifact (#PCDATA)>
        <!ELEMENT scope (#PCDATA)>
        ]>
<assembly xmlns="http://maven.apache.org/plugins/maven-assembly-plugin/assembly/1.1.3"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://maven.apache.org/plugins/maven-assembly-plugin/assembly/1.1.3 http://maven.apache.org/xsd/assembly-1.1.3.xsd">
    <id>btr-zd-publish</id>

    <formats>
        <format>tar.gz</format>
    </formats>

    <fileSets>
        <fileSet>
            <directory>${project.basedir}</directory>
            <outputDirectory>${file.separator}</outputDirectory>
            <fileMode>755</fileMode>
            <includes>
                <include>README.md</include>
            </includes>
        </fileSet>

        <fileSet>
            <directory>${project.basedir}/bin</directory>
            <outputDirectory>bin</outputDirectory>
            <fileMode>755</fileMode>
            <directoryMode>755</directoryMode>
        </fileSet>

        <fileSet>
            <directory>${project.build.outputDirectory}</directory>
            <outputDirectory>config</outputDirectory>
            <fileMode>755</fileMode>
            <directoryMode>755</directoryMode>
            <includes>
                <include>logback.xml</include>
                <include>application.properties</include>
                <include>application.yml</include>
            </includes>
        </fileSet>

    </fileSets>

    <dependencySets>
        <dependencySet>
            <outputDirectory>lib</outputDirectory>
            <useProjectArtifact>true</useProjectArtifact>
            <fileMode>755</fileMode>
            <directoryMode>755</directoryMode>
            <scope>runtime</scope>
        </dependencySet>
    </dependencySets>
</assembly>